### ISSUE TITLE
Workflow issue

### ISSUE THREAD

**Issue by catunderrain** [catunderrain/catunderrain#1]
I want to custom the time to do the 'Action' be the exactly time, but "0 */6 * * *" is make "Action" each 6 hours, right?
```yml
on:
  schedule:
    - cron: "0 */6 * * *"
```
